spring:
  profiles:
  main:
    allow-bean-definition-overriding: true
  session:
    store-type: redis
  redis:
    host: localhost
    password:
    port: 6379

server:
  port: 8443
  http2:
    enabled: true
  ssl:
    key-store: "classpath:keystore.p12"
    key-store-password: changeit
    key-password: changeit

logging:
  level:
    root: info
    org:
      springframework:
        root: info
        core: info
        web: debug
        r2dbc: debug