spring:
  profiles: demo

  demo:
    datasource:
      url: jdbc:postgresql://localhost:5432/demo
      driver-class-name: org.postgresql.Driver
      username: demo_user
      password: demo12341234

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
      show-sql: true
      hibernate:
        ddl-auto: update

    r2dbc:
      name: app
      url: r2dbc:postgresql://app_user:app12341234@localhost:5432/app
      username: app_user
      password: app12341234