spring:
  profiles: quartz
  quartz:
    job-store-type: jdbc
    overwrite-existing-jobs: true
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          datasource:
            url: jdbc:postgresql://localhost:5432/quartz
            driver-class-name: org.postgresql.Driver
            username: postgres
            password: 12341234
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: true
            isClustered: true
          scheduler:
            instanceId: AUTO

